# Generated by Django 6.0.2 on 2026-02-15 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('stack', models.CharField(blank=True, default='', max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=240)),
                ('link', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Abdelhadi ELIDRISSI', max_length=120)),
                ('title', models.CharField(default='Ingénierie Informatique & Réseaux (MIAGE)', max_length=180)),
                ('location', models.CharField(default='Casablanca, Maroc', max_length=120)),
                ('email', models.EmailField(default='elabdolhadi@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+212 7 66 60 81 50', max_length=40)),
                ('headline', models.CharField(default='Je construis des solutions web & SI orientées performance.', max_length=240)),
                ('about', models.TextField(default='Profil orienté solution : autonomie, rigueur, esprit d’analyse et travail d’équipe.')),
                ('internship_note', models.CharField(default='Stage PFA : 2 mois à partir de juin 2026.', max_length=220)),
                ('cv_url', models.CharField(default='', max_length=255)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
